// Curated subset of the Pokémon Base Set (Génération 1).
// 20 Pokémon + 6 énergies de base, suffisant pour un MVP de collection.
// On élargira progressivement (Base Set 102 complète, puis Jungle, etc.).

import type { PokemonCardData } from "./types";

const POKEMON: PokemonCardData[] = [
  // ───────────── Holographic rares ─────────────
  {
    kind: "pokemon",
    id: "base1-4",
    number: 4,
    name: "Dracaufeu",
    type: "fire",
    stage: "stage2",
    evolvesFrom: "Reptincel",
    hp: 120,
    weakness: "water",
    resistance: "fighting",
    retreatCost: 3,
    ability: {
      name: "Brûlure d'Énergie",
      text: "Toute Énergie attachée à Dracaufeu compte comme Énergie Feu.",
    },
    attacks: [
      {
        name: "Tempête de Feu",
        cost: ["fire", "fire", "fire", "fire"],
        damage: 100,
        text: "Défausse 2 Énergies attachées à Dracaufeu.",
      },
    ],
    rarity: "holo-rare",
    flavorText:
      "Crache des flammes assez chaudes pour faire fondre les rochers. A causé des incendies dévastateurs.",
    art: "🔥",
  },
  {
    kind: "pokemon",
    id: "base1-2",
    number: 2,
    name: "Tortank",
    type: "water",
    stage: "stage2",
    evolvesFrom: "Carabaffe",
    hp: 100,
    weakness: "lightning",
    retreatCost: 3,
    ability: {
      name: "Danse Pluie",
      text: "Tu peux attacher autant d'Énergies Eau que tu veux à tes Pokémon ⚡ Eau.",
    },
    attacks: [
      {
        name: "Hydrocanon",
        cost: ["water", "water", "water"],
        damage: 40,
        damageSuffix: "+",
        text: "+10 par Énergie Eau attachée non utilisée pour cette attaque (max +20).",
      },
    ],
    rarity: "holo-rare",
    flavorText: "Lance d'énormes jets d'eau avec une force et une précision incroyables.",
    art: "🌊",
  },
  {
    kind: "pokemon",
    id: "base1-15",
    number: 15,
    name: "Florizarre",
    type: "grass",
    stage: "stage2",
    evolvesFrom: "Herbizarre",
    hp: 100,
    weakness: "fire",
    retreatCost: 2,
    ability: {
      name: "Transfert d'Énergie",
      text: "Aussi souvent que tu veux, déplace une Énergie Plante d'un de tes Pokémon vers un autre.",
    },
    attacks: [
      { name: "Lance-Soleil", cost: ["grass", "grass", "grass", "grass"], damage: 60 },
    ],
    rarity: "holo-rare",
    flavorText: "Une grande fleur fleurit sur son dos. Elle prend les couleurs vives des saisons.",
    art: "🌿",
  },
  {
    kind: "pokemon",
    id: "base1-10",
    number: 10,
    name: "Mewtwo",
    type: "psychic",
    stage: "basic",
    hp: 60,
    weakness: "psychic",
    retreatCost: 3,
    attacks: [
      {
        name: "Psy",
        cost: ["psychic", "psychic", "colorless"],
        damage: 10,
        damageSuffix: "+",
        text: "+10 par Énergie attachée au Pokémon Adverse.",
      },
      {
        name: "Barrière",
        cost: ["psychic", "psychic"],
        text: "Défausse 1 Énergie Psy. Pendant le tour adverse, ignore tous les dégâts subis par Mewtwo.",
      },
    ],
    rarity: "holo-rare",
    flavorText: "Pokémon génétiquement créé. Sa puissance psychique est terrifiante.",
    art: "🧠",
  },
  {
    kind: "pokemon",
    id: "base1-1",
    number: 1,
    name: "Alakazam",
    type: "psychic",
    stage: "stage2",
    evolvesFrom: "Kadabra",
    hp: 80,
    weakness: "psychic",
    retreatCost: 3,
    ability: {
      name: "Échange de Dégâts",
      text: "Une fois par tour, déplace 1 marqueur de dégât d'un de tes Pokémon vers un autre.",
    },
    attacks: [
      {
        name: "Onde Mentale",
        cost: ["psychic", "psychic", "psychic"],
        damage: 30,
        text: "Lance une pièce. Pile, le Pokémon Adverse est Confus.",
      },
    ],
    rarity: "holo-rare",
    art: "🔮",
  },
  {
    kind: "pokemon",
    id: "base1-3",
    number: 3,
    name: "Leveinard",
    type: "colorless",
    stage: "basic",
    hp: 120,
    weakness: "fighting",
    retreatCost: 1,
    attacks: [
      {
        name: "Encaissement",
        cost: ["colorless", "colorless"],
        text: "Lance une pièce. Face, ignore tous les dégâts subis par Leveinard pendant le tour adverse.",
      },
      {
        name: "Damoclès",
        cost: ["colorless", "colorless", "colorless", "colorless"],
        damage: 80,
        text: "Leveinard se fait 80 dégâts à elle-même.",
      },
    ],
    rarity: "holo-rare",
    art: "🥚",
  },
  {
    kind: "pokemon",
    id: "base1-6",
    number: 6,
    name: "Léviator",
    type: "water",
    stage: "stage1",
    evolvesFrom: "Magicarpe",
    hp: 100,
    weakness: "lightning",
    resistance: "fighting",
    retreatCost: 3,
    attacks: [
      { name: "Bulles d'O", cost: ["water", "water", "water"], damage: 40 },
      { name: "Colère", cost: ["water", "water", "water", "water"], damage: 50 },
    ],
    rarity: "holo-rare",
    flavorText: "Pokémon connu pour sa nature violente et féroce.",
    art: "🐉",
  },
  {
    kind: "pokemon",
    id: "base1-7",
    number: 7,
    name: "Tygnon",
    type: "fighting",
    stage: "basic",
    hp: 70,
    weakness: "psychic",
    retreatCost: 2,
    attacks: [
      { name: "Direct", cost: ["fighting"], damage: 20 },
      { name: "Coup Spécial", cost: ["fighting", "fighting", "colorless"], damage: 40 },
    ],
    rarity: "holo-rare",
    art: "🥊",
  },
  {
    kind: "pokemon",
    id: "base1-8",
    number: 8,
    name: "Mackogneur",
    type: "fighting",
    stage: "stage2",
    evolvesFrom: "Machopeur",
    hp: 100,
    weakness: "psychic",
    retreatCost: 3,
    ability: {
      name: "Riposte",
      text: "Quand un Pokémon attaquant blesse Mackogneur, il subit 10 dégâts.",
    },
    attacks: [
      { name: "Frappe Sismique", cost: ["fighting", "fighting", "colorless", "colorless"], damage: 60 },
    ],
    rarity: "holo-rare",
    art: "💪",
  },
  {
    kind: "pokemon",
    id: "base1-16",
    number: 16,
    name: "Électhor",
    type: "lightning",
    stage: "basic",
    hp: 90,
    retreatCost: 3,
    attacks: [
      {
        name: "Tonnerre",
        cost: ["lightning", "lightning", "lightning", "lightning"],
        damage: 60,
        text: "Lance une pièce. Pile, Électhor se fait 30 dégâts à lui-même.",
      },
      {
        name: "Choc-Mental",
        cost: ["lightning"],
        damage: 10,
        text: "Lance une pièce. Face, le Pokémon Adverse est Paralysé.",
      },
    ],
    rarity: "holo-rare",
    art: "⚡",
  },

  // ───────────── Rares non-holo ─────────────
  {
    kind: "pokemon",
    id: "base1-14",
    number: 14,
    name: "Raichu",
    type: "lightning",
    stage: "stage1",
    evolvesFrom: "Pikachu",
    hp: 80,
    weakness: "fighting",
    retreatCost: 1,
    attacks: [
      {
        name: "Vivacité",
        cost: ["lightning", "colorless"],
        damage: 20,
        text: "Lance une pièce. Face, ignore les effets des attaques pendant le tour adverse.",
      },
      {
        name: "Tonnerre",
        cost: ["lightning", "lightning", "colorless", "colorless"],
        damage: 60,
      },
    ],
    rarity: "rare",
    art: "⚡",
  },

  // ───────────── Uncommons ─────────────
  {
    kind: "pokemon",
    id: "base1-46",
    number: 46,
    name: "Reptincel",
    type: "fire",
    stage: "stage1",
    evolvesFrom: "Salamèche",
    hp: 80,
    weakness: "water",
    retreatCost: 1,
    attacks: [
      { name: "Tranche", cost: ["colorless", "colorless", "colorless"], damage: 30 },
      {
        name: "Lance-Flammes",
        cost: ["fire", "fire", "colorless"],
        damage: 50,
        text: "Défausse 1 Énergie Feu attachée à Reptincel.",
      },
    ],
    rarity: "uncommon",
    art: "🦎",
  },
  {
    kind: "pokemon",
    id: "base1-42",
    number: 42,
    name: "Carabaffe",
    type: "water",
    stage: "stage1",
    evolvesFrom: "Carapuce",
    hp: 80,
    weakness: "lightning",
    retreatCost: 1,
    attacks: [
      { name: "Morsure", cost: ["water"], damage: 20 },
      {
        name: "Détourne-Eau",
        cost: ["water", "colorless"],
        damage: 10,
        text: "Lance une pièce. Face, ignore les dégâts pendant le tour adverse.",
      },
    ],
    rarity: "uncommon",
    art: "🐢",
  },
  {
    kind: "pokemon",
    id: "base1-30",
    number: 30,
    name: "Herbizarre",
    type: "grass",
    stage: "stage1",
    evolvesFrom: "Bulbizarre",
    hp: 60,
    weakness: "fire",
    retreatCost: 1,
    attacks: [
      {
        name: "Vampigraine",
        cost: ["grass", "grass"],
        damage: 20,
        text: "Soigne 10 dégâts à Herbizarre.",
      },
    ],
    rarity: "uncommon",
    art: "🌱",
  },

  // ───────────── Commons ─────────────
  {
    kind: "pokemon",
    id: "base1-58",
    number: 58,
    name: "Pikachu",
    type: "lightning",
    stage: "basic",
    hp: 40,
    weakness: "fighting",
    retreatCost: 1,
    attacks: [
      { name: "Mordille", cost: ["colorless"], damage: 10 },
      {
        name: "Choc Foudre",
        cost: ["lightning", "colorless"],
        damage: 30,
        text: "Lance une pièce. Pile, Pikachu se fait 10 dégâts à lui-même.",
      },
    ],
    rarity: "common",
    flavorText: "Quand plusieurs sont rassemblés, l'électricité peut provoquer des orages.",
    art: "⚡",
  },
  {
    kind: "pokemon",
    id: "base1-46-charm",
    number: 46,
    name: "Salamèche",
    type: "fire",
    stage: "basic",
    hp: 50,
    weakness: "water",
    retreatCost: 1,
    attacks: [
      { name: "Griffe", cost: ["colorless"], damage: 10 },
      {
        name: "Flammèche",
        cost: ["fire", "colorless"],
        damage: 30,
        text: "Défausse 1 Énergie Feu attachée à Salamèche.",
      },
    ],
    rarity: "common",
    art: "🦎",
  },
  {
    kind: "pokemon",
    id: "base1-63",
    number: 63,
    name: "Carapuce",
    type: "water",
    stage: "basic",
    hp: 40,
    weakness: "lightning",
    retreatCost: 1,
    attacks: [
      {
        name: "Bulle d'O",
        cost: ["water"],
        damage: 10,
        text: "Lance une pièce. Face, le Pokémon Adverse est Paralysé.",
      },
      {
        name: "Repli",
        cost: ["water", "colorless"],
        text: "Lance une pièce. Face, ignore les dégâts pendant le tour adverse.",
      },
    ],
    rarity: "common",
    art: "🐢",
  },
  {
    kind: "pokemon",
    id: "base1-44",
    number: 44,
    name: "Bulbizarre",
    type: "grass",
    stage: "basic",
    hp: 40,
    weakness: "fire",
    retreatCost: 1,
    attacks: [
      {
        name: "Vampigraine",
        cost: ["grass", "grass"],
        damage: 20,
        text: "Soigne 10 dégâts à Bulbizarre.",
      },
    ],
    rarity: "common",
    art: "🌱",
  },
  {
    kind: "pokemon",
    id: "base1-51",
    number: 51,
    name: "Évoli",
    type: "colorless",
    stage: "basic",
    hp: 50,
    weakness: "fighting",
    retreatCost: 1,
    attacks: [
      { name: "Charge", cost: ["colorless"], damage: 10 },
      { name: "Crocs", cost: ["colorless", "colorless"], damage: 30 },
    ],
    rarity: "common",
    art: "🦊",
  },
  {
    kind: "pokemon",
    id: "base1-35",
    number: 35,
    name: "Magicarpe",
    type: "water",
    stage: "basic",
    hp: 30,
    weakness: "lightning",
    retreatCost: 1,
    attacks: [
      {
        name: "Saute",
        cost: ["water"],
        text: "Lance une pièce. Face, ignore les dégâts pendant le tour adverse.",
      },
      { name: "Trempette", cost: ["water", "colorless", "colorless"], damage: 10 },
    ],
    rarity: "common",
    art: "🐟",
  },

  // ───────────── Énergies de base ─────────────
  {
    kind: "energy",
    id: "base1-energy-fire",
    number: 98,
    name: "Énergie Feu",
    energyType: "fire",
    rarity: "energy",
    art: "🔥",
  },
  {
    kind: "energy",
    id: "base1-energy-water",
    number: 102,
    name: "Énergie Eau",
    energyType: "water",
    rarity: "energy",
    art: "💧",
  },
  {
    kind: "energy",
    id: "base1-energy-grass",
    number: 99,
    name: "Énergie Plante",
    energyType: "grass",
    rarity: "energy",
    art: "🍃",
  },
  {
    kind: "energy",
    id: "base1-energy-lightning",
    number: 100,
    name: "Énergie Électrique",
    energyType: "lightning",
    rarity: "energy",
    art: "⚡",
  },
  {
    kind: "energy",
    id: "base1-energy-psychic",
    number: 101,
    name: "Énergie Psy",
    energyType: "psychic",
    rarity: "energy",
    art: "🌀",
  },
  {
    kind: "energy",
    id: "base1-energy-fighting",
    number: 97,
    name: "Énergie Combat",
    energyType: "fighting",
    rarity: "energy",
    art: "👊",
  },
];

export const POKEMON_BASE_SET: PokemonCardData[] = POKEMON;

export const POKEMON_BASE_SET_BY_ID: Map<string, PokemonCardData> = new Map(
  POKEMON.map((c) => [c.id, c]),
);

export function pokemonCardName(card: PokemonCardData): string {
  return card.name;
}
