import { PLAZA_CONFIG } from "@shared/types";
import type { SceneConfig } from "./scene";

const W = PLAZA_CONFIG.width;
const H = PLAZA_CONFIG.height;

export const PLAZA_SCENE: SceneConfig = {
  width: W,
  height: H,
  backgroundColor: 0x0b0b14,
  floorColor: 0x12121c,
  floorAccentColor: 0xffffff,
  floorAccentAlpha: 0.018,
  landmarks: [
    {
      kind: "portal",
      id: "casino",
      x: 120,
      y: 110,
      color: 0xef4444,
      label: "Casino",
      href: "/play/casino",
    },
    {
      kind: "portal",
      id: "tcg",
      x: W - 120,
      y: 110,
      color: 0x22c55e,
      label: "TCG · Bientôt",
    },
    {
      kind: "portal",
      id: "rpg",
      x: 120,
      y: H - 110,
      color: 0xf59e0b,
      label: "RPG · Bientôt",
    },
    {
      kind: "portal",
      id: "medieval",
      x: W - 120,
      y: H - 110,
      color: 0x6366f1,
      label: "Médiéval · Bientôt",
    },
    {
      kind: "portal",
      id: "tycoon",
      x: W / 2,
      y: 90,
      color: 0xec4899,
      label: "Tycoon · Bientôt",
    },
  ],
};

export const CASINO_SCENE: SceneConfig = {
  width: W,
  height: H,
  backgroundColor: 0x150606,
  floorColor: 0x1f0a0a,
  floorAccentColor: 0xef4444,
  floorAccentAlpha: 0.05,
  landmarks: [
    {
      kind: "portal",
      id: "back-to-plaza",
      x: 80,
      y: 80,
      color: 0x6366f1,
      label: "← Plaza",
      href: "/play",
    },
    {
      kind: "table",
      id: "blackjack-1",
      x: W / 2,
      y: H / 2,
      width: 220,
      height: 130,
      feltColor: 0x065f3e,
      accentColor: 0xeab308,
      label: "Blackjack",
      seats: 5,
    },
    {
      kind: "table",
      id: "hilo-1",
      x: 220,
      y: H / 2 + 40,
      width: 140,
      height: 100,
      feltColor: 0x7c2d12,
      accentColor: 0xfbbf24,
      label: "Hi-Lo · Bientôt",
      seats: 1,
    },
    {
      kind: "table",
      id: "roulette-1",
      x: W - 220,
      y: H / 2 + 40,
      width: 160,
      height: 110,
      feltColor: 0x064e3b,
      accentColor: 0xef4444,
      label: "Roulette · Bientôt",
      seats: 8,
    },
    {
      kind: "table",
      id: "slots-1",
      x: 220,
      y: H - 160,
      width: 120,
      height: 90,
      feltColor: 0x4c1d95,
      accentColor: 0xa78bfa,
      label: "Slots · Bientôt",
      seats: 1,
    },
    {
      kind: "table",
      id: "poker-1",
      x: W - 220,
      y: H - 160,
      width: 180,
      height: 120,
      feltColor: 0x0c4a6e,
      accentColor: 0xf59e0b,
      label: "Poker · Bientôt",
      seats: 6,
    },
    {
      kind: "table",
      id: "mines-1",
      x: W / 2,
      y: H - 160,
      width: 130,
      height: 100,
      feltColor: 0x1e293b,
      accentColor: 0x10b981,
      label: "Mines · Bientôt",
      seats: 1,
    },
  ],
};
